# Generated by Django 3.1.7 on 2021-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210513_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='f_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='l_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
