# Generated by Django 3.1.7 on 2021-05-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
