# Generated by Django 3.2.3 on 2021-05-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210524_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('is_ready_to_pay', 'Can now pay for his items')]},
        ),
    ]
