# Generated by Django 3.2.3 on 2021-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='can_pay',
            field=models.BooleanField(default=False),
        ),
    ]
