# Generated by Django 3.2.3 on 2021-05-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_is_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payed',
        ),
    ]
